lang = {
    "en": {
        "server-error": "Server Error! ",
        "post-added": "Post added",
        "updated": "Updated",
        "not-found": "Not found",
        "deleted": "Deleted",
        "message_updated": "Message updated",
        "cannot-self-message": "Cannot send message to yourself",
        "message-not-found-not-exist": "Message not found or does not exist",
        "group-exist": "Group already exist",
        "group-create": "Group added",
        "sent": "Sent",
        "joint-group": "Joined group",
        "cannot-see-group-messages-not-part-off": "You cannot see messages in groups your not part off",
        "group-not-found": "Group not found or dosen't exist anymore",
        "empty-list-set": "Provide list set is empty",
        "account-not-found": "Account not found",
        "school-create-failed": "Permission denied insufficient account access to create school account",
        "school-created": "school account created",
        "school-exist": "School already exist",
        "account-type-created": "Account type created",
        "school-type-denied": "Only administrators are permited to create school types",
        "added": "Added",
        "added-to-school": "Was added to",
        "school-member-denied": "Only administrators are permited to create school members",
        "unauthorized-operation": "Unauthorized operation",
        "school-level-exist": "School level exist",
        "no-such-account-school": "No such account in your school",
        "mail-taken": "Email already taken",
        "account-username-password-exist": "Account username or password already taken"
    },
    "fr": {
        "updated": "Mis à jour",
        "server-error": "Erreur du serveur",
        "post-added": "Post ajouté",
        "not-found": "La demande n'existe pas",
        "deleted": "Supprimé",
        "message_updated": "Message mise a jour",
        "cannot-self-message": "Impossible d'envoyer un message à vous-même",
        "message-not-found-not-exist": "Message non trouvé ou n'existe pas",
        "group-exist": "Ce groupe existe deja",
        "group-create": "Groupe ajouté",
        "sent": "Envoyer",
        "joint-group": "Ajouter dans le group",
        "cannot-see-group-messages-not-part-off": "Vous ne pouvez pas voir les messages dans les groupes si vous n'en faites pas partie",
        "group-not-found": "Groupe non trouvé ou n'existe plus",
        "empty-list-set": "La liste fournie est vide",
        "account-not-found": "Compte non trouvé",
        "school-create-failed": "Autorisation refusée d'accès au compte insuffisant pour créer un compte d'école",
        "school-created": "compte d'école créé",
        "school-exist": "L'école existe déjà",
        "account-type-created": "Type de compte créé",
        "school-type-denied": "Seuls les administrateurs sont autorisés à créer des types d'école",
        "added": "Ajoutée",
        "added-to-school": "A été ajouté à",
        "school-member-denied": "Seuls les administrateurs sont autorisés à créer les membres d'école",
        "unauthorized-operation": "Opération non autorisée",
        "school-level-exist": "Ce niveau scolaire existe déjà",
        "not-such-account-school": "Pas un tel compte dans votre école",
        "mail-taken": "Adresse e-mail déjà prise",
        "account-username-password-exist": "Nom d'utilisateur ou mot de passe déjà utilisé"
    },
    "tr": {},
    "ch": {},
    "ru": {}
}